# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSvJ-spMdlSBEtGWqadwBHHEWByrpAHK
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample movie database (title and description/tags)
movies = [
    {"title": "Inception", "tags": "dream sci-fi action thriller mind-bending"},
    {"title": "The Notebook", "tags": "romance drama emotional love"},
    {"title": "Interstellar", "tags": "space sci-fi emotional time travel"},
    {"title": "The Dark Knight", "tags": "action superhero crime thriller"},
    {"title": "La La Land", "tags": "romance music drama dreams"},
    {"title": "The Martian", "tags": "space survival sci-fi humor"},
]

# User preference input
user_input = input("Describe the kind of movie you want to watch: ")

# Combine movie tags and user input for vectorization
corpus = [movie["tags"] for movie in movies]
corpus.append(user_input)

# Convert text to vectors
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(corpus)

# Calculate similarity between user input and all movies
similarity_scores = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1])

# Get top recommended movie index
top_index = similarity_scores.argsort()[0][-1]

# Output result
print("\nRecommended Movie for You:")
print(f"{movies[top_index]['title']} - Tags: {movies[top_index]['tags']}")